name: Deploy Website v31

on:
  push:
    branches:
      - main   # deploy khi push lên nhánh main
  pull_request:

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: |
          npm install -g serve
          echo "No deps for static site, just HTML/CSS/JS"

      - name: Build (optional)
        run: |
          mkdir dist
          cp index.v31.html dist/index.html
          cp style.v31.css dist/style.css
          cp script.v31.js dist/script.js
          cp -r img dist/img

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: gh-pages
